{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ template "errbit-helm.fullname" . }}
  labels:
    app: {{ template "errbit-helm.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "errbit-helm.name" . }}
  ingress:
    # Allow inbound connections
    - ports:
      - port: {{ .Values.service.externalPort }}
  # Allow all egress traffic
  egress:
    - {}
{{- end }}
